// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/cshum/imagor-studio/server/ent/schema"
	"github.com/cshum/imagor-studio/server/ent/storage"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storageFields := schema.Storage{}.Fields()
	_ = storageFields
	// storageDescName is the schema descriptor for name field.
	storageDescName := storageFields[0].Descriptor()
	// storage.NameValidator is a validator for the "name" field. It is called by the builders before save.
	storage.NameValidator = storageDescName.Validators[0].(func(string) error)
	// storageDescKey is the schema descriptor for key field.
	storageDescKey := storageFields[1].Descriptor()
	// storage.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	storage.KeyValidator = storageDescKey.Validators[0].(func(string) error)
	// storageDescType is the schema descriptor for type field.
	storageDescType := storageFields[2].Descriptor()
	// storage.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	storage.TypeValidator = storageDescType.Validators[0].(func(string) error)
	// storageDescConfig is the schema descriptor for config field.
	storageDescConfig := storageFields[3].Descriptor()
	// storage.ConfigValidator is a validator for the "config" field. It is called by the builders before save.
	storage.ConfigValidator = storageDescConfig.Validators[0].(func(string) error)
	// storageDescCreatedAt is the schema descriptor for created_at field.
	storageDescCreatedAt := storageFields[4].Descriptor()
	// storage.DefaultCreatedAt holds the default value on creation for the created_at field.
	storage.DefaultCreatedAt = storageDescCreatedAt.Default.(func() time.Time)
	// storageDescUpdatedAt is the schema descriptor for updated_at field.
	storageDescUpdatedAt := storageFields[5].Descriptor()
	// storage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storage.DefaultUpdatedAt = storageDescUpdatedAt.Default.(func() time.Time)
	// storage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storage.UpdateDefaultUpdatedAt = storageDescUpdatedAt.UpdateDefault.(func() time.Time)
}
