version: '3.8'

services:
  imagor-studio:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # Add your environment variables here
      # - DATABASE_URL=postgres://user:password@db:5432/imagor_studio
      # - JWT_SECRET=your-jwt-secret
      # - IMAGOR_URL=http://imagor:8080
    volumes:
      # Optional: Mount local storage for development
      # - ./data:/data
    restart: unless-stopped
    
  # Optional: Add a database service
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: imagor_studio
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Optional: Add imagor service for image processing
  # imagor:
  #   image: shumc/imagor:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PORT=8080
  #     - IMAGOR_UNSAFE=1  # Only for development
  #   restart: unless-stopped

# volumes:
#   postgres_data:
