# Development environment with hot reload and external imagor
version: "3.8"

services:
  # External Imagor service for image processing (development)
  imagor:
    image: shumc/imagor:latest
    container_name: imagor-studio-imagor-dev
    environment:
      PORT: 8000
      IMAGOR_UNSAFE: 1  # Unsafe mode for development

      # File storage configuration
      FILE_LOADER_BASE_DIR: /mnt/data/images
      FILE_RESULT_STORAGE_BASE_DIR: /mnt/data/result
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666

      SERVER_CORS: true
    volumes:
      - ./test-data:/mnt/data  # Mount server storage directory
    ports:
      - "8000:8000"
    networks:
      - imagor-studio-dev

networks:
  imagor-studio-dev:
    driver: bridge
