package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, storageKey *string, path string, content graphql.Upload) (bool, error) {
	panic(fmt.Errorf("not implemented: UploadFile - uploadFile"))
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, storageKey *string, path string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, storageKey *string, path string) (bool, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// AddStorageConfig is the resolver for the addStorageConfig field.
func (r *mutationResolver) AddStorageConfig(ctx context.Context, config StorageConfigInput) (*StorageConfig, error) {
	panic(fmt.Errorf("not implemented: AddStorageConfig - addStorageConfig"))
}

// UpdateStorageConfig is the resolver for the updateStorageConfig field.
func (r *mutationResolver) UpdateStorageConfig(ctx context.Context, key string, config StorageConfigInput) (*StorageConfig, error) {
	panic(fmt.Errorf("not implemented: UpdateStorageConfig - updateStorageConfig"))
}

// DeleteStorageConfig is the resolver for the deleteStorageConfig field.
func (r *mutationResolver) DeleteStorageConfig(ctx context.Context, key string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteStorageConfig - deleteStorageConfig"))
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, storageKey *string, path string, offset int, limit int, onlyFiles *bool, onlyFolders *bool, sortBy *SortOption, sortOrder *SortOrder) (*FileList, error) {
	panic(fmt.Errorf("not implemented: ListFiles - listFiles"))
}

// StatFile is the resolver for the statFile field.
func (r *queryResolver) StatFile(ctx context.Context, storageKey *string, path string) (*FileStat, error) {
	panic(fmt.Errorf("not implemented: StatFile - statFile"))
}

// ListStorageConfigs is the resolver for the listStorageConfigs field.
func (r *queryResolver) ListStorageConfigs(ctx context.Context) ([]*StorageConfig, error) {
	panic(fmt.Errorf("not implemented: ListStorageConfigs - listStorageConfigs"))
}

// GetStorageConfig is the resolver for the getStorageConfig field.
func (r *queryResolver) GetStorageConfig(ctx context.Context, key string) (*StorageConfig, error) {
	panic(fmt.Errorf("not implemented: GetStorageConfig - getStorageConfig"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
