// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type File struct {
	Name        string  `json:"name"`
	Path        string  `json:"path"`
	Size        int     `json:"size"`
	IsDirectory bool    `json:"isDirectory"`
	Content     *string `json:"content,omitempty"`
}

type FileList struct {
	Items      []*File `json:"items"`
	TotalCount int     `json:"totalCount"`
}

type Mutation struct {
}

type Query struct {
}
