// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type File struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	Size        int    `json:"size"`
	IsDirectory bool   `json:"isDirectory"`
}

type FileList struct {
	Items      []*File `json:"items"`
	TotalCount int     `json:"totalCount"`
}

type FileStat struct {
	Name         string  `json:"name"`
	Path         string  `json:"path"`
	Size         int     `json:"size"`
	IsDirectory  bool    `json:"isDirectory"`
	ModifiedTime string  `json:"modifiedTime"`
	Etag         *string `json:"etag,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
