package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.51

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/cshum/imagor-studio/server/internal/storagemanager"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/cshum/imagor-studio/server/internal/storage"
	"go.uber.org/zap"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, storageKey *string, path string, content graphql.Upload) (bool, error) {
	r.logger.Info("Uploading file", zap.String("path", path), zap.String("filename", content.Filename))

	s, err := r.getStorage(storageKey)
	if err != nil {
		return false, err
	}

	err = s.Put(ctx, path, content.File)
	if err != nil {
		r.logger.Error("Failed to upload file", zap.Error(err))
		return false, fmt.Errorf("failed to upload file: %w", err)
	}

	return true, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, storageKey *string, path string) (bool, error) {
	r.logger.Info("Deleting file", zap.String("path", path))

	s, err := r.getStorage(storageKey)
	if err != nil {
		return false, err
	}

	err = s.Delete(ctx, path)
	if err != nil {
		r.logger.Error("Failed to delete file", zap.Error(err))
		return false, fmt.Errorf("failed to delete file: %w", err)
	}

	return true, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, storageKey *string, path string) (bool, error) {
	r.logger.Info("Creating folder", zap.String("path", path))

	s, err := r.getStorage(storageKey)
	if err != nil {
		return false, err
	}

	err = s.CreateFolder(ctx, path)
	if err != nil {
		r.logger.Error("Failed to create folder", zap.Error(err))
		return false, fmt.Errorf("failed to create folder: %w", err)
	}

	return true, nil
}

// AddStorageConfig is the resolver for the addStorageConfig field.
func (r *mutationResolver) AddStorageConfig(ctx context.Context, input StorageConfigInput) (*StorageConfig, error) {
	var rawConfig json.RawMessage
	err := json.Unmarshal([]byte(input.Config), &rawConfig)
	if err != nil {
		return nil, err
	}

	cfg := storagemanager.StorageConfig{
		Name:   input.Name,
		Key:    input.Key,
		Type:   input.Type,
		Config: rawConfig,
	}

	err = r.storageManager.AddConfig(cfg)
	if err != nil {
		return nil, err
	}

	return &StorageConfig{
		Name:   cfg.Name,
		Key:    cfg.Key,
		Type:   cfg.Type,
		Config: input.Config, // Use the original string input
	}, nil
}

// UpdateStorageConfig is the resolver for the updateStorageConfig field.
func (r *mutationResolver) UpdateStorageConfig(ctx context.Context, key string, input StorageConfigInput) (*StorageConfig, error) {
	var rawConfig json.RawMessage
	err := json.Unmarshal([]byte(input.Config), &rawConfig)
	if err != nil {
		return nil, err
	}

	cfg := storagemanager.StorageConfig{
		Name:   input.Name,
		Key:    input.Key,
		Type:   input.Type,
		Config: rawConfig,
	}

	err = r.storageManager.UpdateConfig(key, cfg)
	if err != nil {
		return nil, err
	}

	return &StorageConfig{
		Name:   cfg.Name,
		Key:    cfg.Key,
		Type:   cfg.Type,
		Config: input.Config, // Use the original string input
	}, nil
}

// DeleteStorageConfig is the resolver for the deleteStorageConfig field.
func (r *mutationResolver) DeleteStorageConfig(ctx context.Context, key string) (bool, error) {
	err := r.storageManager.DeleteConfig(key)
	if err != nil {
		return false, err
	}
	return true, nil
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, storageKey *string, path string, offset int, limit int, onlyFiles *bool, onlyFolders *bool, sortBy *SortOption, sortOrder *SortOrder) (*FileList, error) {
	r.logger.Info("Listing files",
		zap.String("path", path),
		zap.Int("offset", offset),
		zap.Int("limit", limit),
		zap.Any("sortBy", sortBy),
		zap.Any("sortOrder", sortOrder),
	)

	s, err := r.getStorage(storageKey)
	if err != nil {
		return nil, err
	}

	options := storage.ListOptions{
		Offset:      offset,
		Limit:       limit,
		OnlyFiles:   onlyFiles != nil && *onlyFiles,
		OnlyFolders: onlyFolders != nil && *onlyFolders,
	}

	if sortBy != nil {
		switch *sortBy {
		case SortOptionName:
			options.SortBy = storage.SortByName
		case SortOptionSize:
			options.SortBy = storage.SortBySize
		case SortOptionModifiedTime:
			options.SortBy = storage.SortByModifiedTime
		default:
			return nil, fmt.Errorf("invalid sortBy option: %s", *sortBy)
		}
	}

	if sortOrder != nil {
		switch *sortOrder {
		case SortOrderAsc:
			options.SortOrder = storage.SortOrderAsc
		case SortOrderDesc:
			options.SortOrder = storage.SortOrderDesc
		default:
			return nil, fmt.Errorf("invalid sortOrder option: %s", *sortOrder)
		}
	}

	result, err := s.List(ctx, path, options)
	if err != nil {
		r.logger.Error("Failed to list files", zap.Error(err))
		return nil, fmt.Errorf("failed to list files: %w", err)
	}

	files := make([]*File, len(result.Items))
	for i, item := range result.Items {
		files[i] = &File{
			Name:        item.Name,
			Path:        item.Path,
			Size:        int(item.Size),
			IsDirectory: item.IsDir,
		}
	}

	return &FileList{
		Items:      files,
		TotalCount: result.TotalCount,
	}, nil
}

// StatFile is the resolver for the statFile field.
func (r *queryResolver) StatFile(ctx context.Context, storageKey *string, path string) (*FileStat, error) {
	r.logger.Info("Getting file stats", zap.String("path", path))

	s, err := r.getStorage(storageKey)
	if err != nil {
		return nil, err
	}

	fileInfo, err := s.Stat(ctx, path)
	if err != nil {
		r.logger.Error("Failed to get file stats", zap.Error(err))
		return nil, fmt.Errorf("failed to get file stats: %w", err)
	}

	return &FileStat{
		Name:         fileInfo.Name,
		Path:         fileInfo.Path,
		Size:         int(fileInfo.Size),
		IsDirectory:  fileInfo.IsDir,
		ModifiedTime: fileInfo.ModifiedTime.Format(time.RFC3339),
		Etag:         &fileInfo.ETag,
	}, nil
}

// ListStorageConfigs is the resolver for the listStorageConfigs field.
func (r *queryResolver) ListStorageConfigs(ctx context.Context) ([]*StorageConfig, error) {
	configs := r.storageManager.GetConfigs()
	result := make([]*StorageConfig, len(configs))
	for i, cfg := range configs {
		configStr, err := json.Marshal(cfg.Config)
		if err != nil {
			return nil, err
		}
		result[i] = &StorageConfig{
			Name:   cfg.Name,
			Key:    cfg.Key,
			Type:   cfg.Type,
			Config: string(configStr),
		}
	}
	return result, nil
}

// GetStorageConfig is the resolver for the getStorageConfig field.
func (r *queryResolver) GetStorageConfig(ctx context.Context, key string) (*StorageConfig, error) {
	cfg, ok := r.storageManager.GetConfig(key)
	if !ok {
		return nil, nil
	}
	configStr, err := json.Marshal(cfg.Config)
	if err != nil {
		return nil, err
	}
	return &StorageConfig{
		Name:   cfg.Name,
		Key:    cfg.Key,
		Type:   cfg.Type,
		Config: string(configStr),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
