export {
  accountAdminGeneralRoute,
  accountAdminImagorRoute,
  accountAdminIndexRoute,
  accountAdminLayoutRoute,
  accountAdminLicenseRoute,
  accountAdminStorageRoute,
  accountLayoutRoute,
  accountProfileRoute,
  accountRedirectRoute,
  adminSetupRoute,
  authCallbackRoute,
  baseLayoutRoute,
  canvasEditorRoute,
  galleryCanvasEditorRoute,
  galleryImageEditorRoute,
  galleryRoute,
  imagePage,
  loginRoute,
  rootImageEditorRoute,
  rootPathBeforeLoad,
  rootRoute,
  settingsLayoutRoute,
} from '@/router/shared-routes'
