name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Docker Test
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: server-builder
          tags: imagor-studio-test
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Run web tests in Docker
#        run: |
#          docker run --rm \
#            -v ${{ github.workspace }}:/workspace \
#            -w /workspace/web \
#            node:22-alpine \
#            sh -c "npm ci && npm run type-check && npm run lint && npm run build"

      - name: Run web tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/web \
            node:22-alpine \
            sh -c "npm ci && npm run build"

      - name: Run server tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            imagor-studio-test \
            sh -c "cd server && go test ./... -v"

      - name: Run server tests with coverage in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            imagor-studio-test \
            sh -c "cd server && go test -coverprofile=coverage.out ./..."
